// components/OutboundLink.vue
<!--
From VuePress
https://github.com/vuejs/vuepress/blob/81cce3967c018fe005f112cbe950abc7457dbacb/packages/%40vuepress/core/lib/client/components/OutboundLink.vue
-->
<template>
  <span class="outbound-link-indicator">
    <svg
      class="icon outbound"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      focusable="false"
      x="0px"
      y="0px"
      viewBox="0 0 100 100"
      width="15"
      height="15"
    >
      <path
        fill="currentColor"
        d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"
      />
      <polygon
        fill="currentColor"
        points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"
      /></svg
    ><!--
    --><span class="sr-only">{{ openInNewWindowTitle }}</span>
  </span>
</template>

<script>
export default {
  computed: {
    openInNewWindowTitle() {
      return '(opens new window)'
    },
  },
}
</script>

<style>
figure img + .outbound-link-indicator {
  display: none;
}

.icon.outbound {
  color: #aaa;
  display: inline-block;
  vertical-align: middle;
  position: relative;
  top: -1px;
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}
</style>

// src/packlets/svelte-runtime/OutboundLink.svelte
<span class="indicator"
  ><svg
    class="icon"
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
    viewBox="0 0 100 100"
    width="15"
    height="15"
    ><path
      fill="currentColor"
      d="M18.8 85.1h56c2.2 0 4-1.8 4-4v-32h-8v28h-48v-48h28v-8h-32c-2.2 0-4 1.8-4 4v56c0 2.2 1.8 4 4 4z"
    /><path
      fill="currentColor"
      d="m45.7 48.7 5.6 5.6 25.9-25.8v8.7h8V14.9H62.8v8h8.7z"
    /></svg
  ><span class="srOnly"> (opens new window)</span></span
>

<style>
  :global(figure) :global(img) + .indicator {
    display: none;
  }
  .icon {
    color: #aaa;
    display: inline-block;
    vertical-align: middle;
    position: relative;
    top: -1px;
  }
  .srOnly {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0;
  }
</style>
