// src/packlets/vue-app-react/index.tsx
import { useEffect, useLayoutEffect, useRef } from "react"
import { Vue } from "../vue-runtime"

export interface VueComponentBasis {
  render: string
  staticRenderFns: string[]
  componentModule: string | null
}

export interface VueApp {
  renderer: "vue"
  basis: VueComponentBasis
  html: string
}

function compileAndExecuteModule(code: string) {
  const fn = new Function("module", "exports", "Vue", code)
  const myModule = { exports: {} as any }
  fn(myModule, myModule.exports, Vue)
  return myModule.exports.default
}

export function createVueComponentOptions(basis: VueComponentBasis) {
  const component = {
    components: {},
  }
  // Object.assign(component.components, { OutboundLink, DSplit, NotesLink })
  if (basis.componentModule) {
    Object.assign(component, compileAndExecuteModule(basis.componentModule))
  }
  Object.assign(component, {
    render: new Function(basis.render),
    staticRenderFns: basis.staticRenderFns.map((f) => new Function(f)),
  })
  return component
}

export const VueApp = ({ basis, html }: VueApp) => {
  const domRef = useRef<HTMLDivElement>(null)
  useLayoutEffect(() => {
    if (!domRef.current) return
    if (!("Vue" in window)) Object.assign(window, { Vue })
    const app = new (Vue as any)(createVueComponentOptions(basis))
    app.$mount(domRef.current.firstElementChild!)
  }, [basis])
  return (
    <div
      data-vue-root
      ref={domRef}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}

// src/packlets/svelte-app-react/index.tsx
import { useLayoutEffect, useRef } from "react"
import * as svelteInternal from "svelte/internal"

export interface SvelteApp {
  renderer: "svelte"
  js: Record<string, string>
  css: string
  html: string
}

function compileSvelteComponents(js: Record<string, string>) {
  const vars: Record<string, any> = {}
  for (const [name, code] of Object.entries(js)) {
    vars[name] = compileAndExecuteModule(code, vars)
  }
  return vars
}

function compileAndExecuteModule(code: string, vars: Record<string, any> = {}) {
  const entries = Object.entries(vars)
  const keys = entries.map(([key]) => key)
  const values = entries.map(([_, value]) => value)
  const fn = new Function("module", "exports", "require", ...keys, code)
  const myModule = { exports: {} as any }
  const childRequire = (specifier: string) => {
    if (specifier === "svelte/internal") return svelteInternal
    throw new Error('Unsupported require("' + specifier + '")')
  }
  fn(myModule, myModule.exports, childRequire, ...values)
  return myModule.exports.default
}

export const SvelteApp = ({ js, css, html }: SvelteApp) => {
  const domRef = useRef<HTMLDivElement>(null)
  useLayoutEffect(() => {
    if (!domRef.current) return
    const SvelteComponents = compileSvelteComponents(js)
    const app = new SvelteComponents.NoteRenderer({
      target: domRef.current,
      hydrate: true,
    })
    return () => {
      app.$destroy()
    }
  }, [js])
  return (
    <>
      <style>{css}</style>
      <div
        data-svelte-root
        ref={domRef}
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </>
  )
}
